---
functional:
  - пользователь должен иметь возможность авторизоваться через электонную почту, аккаунт Github, или аккаунт Discord.
  - Пользователь может создать аккаунт без привязки к другим ресурсам. 
  - пользователь имеет личный кабинет на сайте, где отображена статистика активности, а также статистика игр.
  - пользователь может играть с ботом без регистрации на сайте. 
  - на сайте есть общий рейтинг всех пользователей.
  - пользователь может выбрать уровень сложности игры.
  - пользователь может выбрать язык программировнаия. 
  - пользователь может играть с ботом, с другим пользователем или с другом по ссылке.
  - пользователь может выбрать продолжительность игры.
  - пользователь может выбрать конкретное или случайное задание для игры.
  - пользователь может присоединиться к уже созданной ботом или другим пользователем игре.
  - пользователь может наблюдать за игрой в качестве зрителя.
  - пользователь может создать турнир.
  - пользователь может оставлять комментарии

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - на сайте должно быть описание проекта. 
  - пользователь может изменить пароль входа в аккаунт.